# Generated by Django 4.1.7 on 2023-02-17 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exgaustersignaldescription",
            name="Exgauster",
        ),
    ]
