# Generated by Django 4.1.7 on 2023-02-17 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_remove_exgaustersignaldescription_exgauster"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exgaustersignaldescription",
            unique_together={("place_x", "place_y", "type")},
        ),
    ]
