# Generated by Django 4.1.7 on 2023-02-17 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_alter_exgaustersignaldescription_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exgauster",
            name="installed",
        ),
    ]
