# Generated by Django 4.1.7 on 2023-02-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_remove_exgauster_installed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exgaustersignal",
            old_name="Exgauster",
            new_name="exgauster",
        ),
        migrations.AddField(
            model_name="exgaustersignal",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exgaustersignal",
            name="comment",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="exgaustersignal",
            name="place_x",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exgaustersignal",
            name="place_y",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exgaustersignal",
            name="type",
            field=models.CharField(
                choices=[("analog", "ANALOG"), ("digital", "DIGITAL")],
                default="analog",
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="exgaustersignal",
            unique_together={("place_x", "place_y", "type")},
        ),
        migrations.RemoveField(
            model_name="exgaustersignal",
            name="signal",
        ),
        migrations.DeleteModel(
            name="ExgausterSignalDescription",
        ),
    ]
