# Generated by Django 4.1.7 on 2023-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_rename_exgauster_exgaustersignal_exgauster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exgaustersignal",
            name="characteristics",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="exgaustersignal",
            name="characteristics_description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="exgaustersignal",
            name="item",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="exgaustersignal",
            name="item_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
