# Generated by Django 4.1.7 on 2023-02-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0008_alter_exgausterrecordapproximationsignal_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["offset"]},
        ),
        migrations.AlterField(
            model_name="exgausterrecordapproximationsignal",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signals",
                to="analytics.recordapproximation",
            ),
        ),
    ]
