# Generated by Django 4.1.7 on 2023-02-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0009_alter_record_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exgaustersignal",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installations",
                to="analytics.exgaustersignal",
            ),
        ),
    ]
